### ISSUE TITLE
タブのセレクタの指定に関して

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/tabChange#1]
https://github.com/YukaMurata/tabChange/blob/master/js/tabChange.js#L3

現在、タブのセレクタを`$('a[href^="#"]')`で指定していますが、この指定方法だと影響範囲が広くてちょっと危ないです。
ページ内リンクやスクロールも`<a href="#content1">1</a>`のような記述であることが多いためそれらをクリックした時も処理が実行されてしまい、思わぬ誤動作を招く可能性があります。
そのため、クラスなどを付与してそれらを指定した方が良いかもしれないです。

上記の懸念は認識済みであり、今回はタブのみなのでこの書き方にしたのであれば問題ありません。
（私もこういう書き方をしてしまうことはあるので状況に応じて使い分けてください。）

**Comment by YukaMurata** [comment]
承知しました。
ありがとうございます。
