### ISSUE TITLE
.button_aと.button_bに関して

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/tabChange#2]
https://github.com/YukaMurata/tabChange/blob/master/sass/index.scss#L12-L38

現在、`.button_a`と`.button_b`にそれぞれ同じようなスタイルを適用しているようですが、分けている理由はありますか。

仕様上こうする理由があったらこのままで問題ありませんが、特に理由がないのであれば分けずに`.button`にスタイルを適用するよう修正していただけますか。

**Comment by YukaMurata** [comment]
上記、対応いたしましたの確認よろしくお願いいたします。
989db32
(案件では、それぞれのボタンの色等が変わるのでは？と思い、別々のクラスにしていました..。どっちにしろ、色用のスタイルを当てればよいので、基本のボタンのスタイルは統一します。)

**Comment by liberta793** [comment]
確認できました!
>色用のスタイルを当てればよいので、基本のボタンのスタイルは統一します。

そうですね。そのように対応すれば問題ないかと思います。
