### ISSUE TITLE
HTMLのスペースにばらつきがある、余計なスペースが存在する

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/tabChange#3]
https://github.com/YukaMurata/tabChange/blob/master/index.html#L10-L23
HTMLのスペースにばらつきがある。余計なスペースが存在するため修正していただけますか。

修正していただきたい理由は以下と同様です。
https://github.com/YukaMurata/modal/issues/17

**Comment by YukaMurata** [comment]
すみません。
スペースを統一いたしました。
確認よろしくお願いいたします。
ad5025c
b3f603e

**Comment by liberta793** [comment]
確認できました!
