### ISSUE TITLE
タブのクリック判定エリアが狭い

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/tabChange#4]
現在、以下の青色の箇所のみをクリックした時しかタブが切り替わらないです。

![button](https://cloud.githubusercontent.com/assets/13026287/23843367/aa969792-07fe-11e7-82f4-198f16cb6f63.jpg)

タブのどこをクリックしても処理が実行されるようにスタイルを修正していただけますか。

**Comment by YukaMurata** [comment]
上記、対応いたしましたので確認よろしくお願いいたします。
989db32

**Comment by liberta793** [comment]
確認できました!
