### ISSUE TITLE
preventDefaultを利用する

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/tabChange#5]
現在、タブをクリックするとページのURLにアンカー名が付与されてが以下のようになると思います

https://yukamurata.github.io/tabChange/index.html#content1

アンカー名を付与する必要があれば問題あいませんが、必要なければ以下のようにクリック処理の中にpreventDefaultを追加していただけますか。

```
$('a[href^="#"]').click(function(e){
    e.preventDefault();
});
```

**Comment by YukaMurata** [comment]
上記、対応いたしましたので
確認よろしくお願いいたします。
c737455

**Comment by liberta793** [comment]
確認できました!
