### ISSUE TITLE
タブのセレクタの指定に関して その2

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/tabChange#6]
https://github.com/YukaMurata/tabChange/blob/master/js/tabChange.js#L13

`$('.button p');`

https://github.com/YukaMurata/tabChange/issues/1
は状況に応じて対応していただければ良いですが、
これは影響範囲が広すぎて危ないです（.button以下の全てのpタグが指定されてしまうため）。

そのため、指定するセレクタにクラスを付与するか`$('.button > p');`のように.button直下のpタグを指定するように修正していただけますか。

**Comment by YukaMurata** [comment]
pタグを指定せず、クラスを付与し、それを指定するように対応いたしました。
確認よろしくお願いいたします。
c19205f

**Comment by liberta793** [comment]
確認できました!
