### ISSUE TITLE
コンフリクトしたファイルがあがっている

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/tabChange#7]
コンフリクトしたファイルがあがってしまっているため、
お手隙の際に修正していただけますか。

https://github.com/YukaMurata/tabChange/blob/master/js/tabChange.js

**Comment by YukaMurata** [comment]
コンフリクトを直しました。
確認よろしくお願いいたします。 
b74029c

**Comment by liberta793** [comment]
確認できました!
