### ISSUE TITLE
等価演算子ではなく、厳密等価演算子を使う

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/tabChange#8]
https://github.com/YukaMurata/tabChange/blob/master/js/tabChange.js#L10

現在、等価演算子（==、!= 等）を利用しているようですが、厳密等価演算子（===、!== 等）を利用してください。
等価演算子を利用すると予期せず動作を招く可能性があるため、理由がなければ基本的には厳密等価演算子を利用すべきです。

以下参考です。

- [JavaScript 忘れがちな　=== と == の違い](http://qiita.com/PianoScoreJP/items/e43d70ec188c6fed73ed)
- [javascriptの比較演算子と厳密比較演算子の挙動について](http://unskilled.site/javascript_hikakuennzannshi/)

**Comment by YukaMurata** [comment]
参考資料ありがとうございます。
対応しましたので、確認よろしくお願いいたします。
663c9cb

**Comment by liberta793** [comment]
確認できました!
