### ISSUE TITLE
不要な制御構文の記述は削除する

### ISSUE THREAD

**Issue by liberta793** [YukaMurata/tabChange#9]
https://github.com/YukaMurata/tabChange/blob/master/js/tabChange.js#L10-L12

こちら作業途中でしょうか。
もし対応済みの場合、これはまずいので空の制御構文を消しても動くように修正をしてください。

**Comment by YukaMurata** [comment]
対応しましたので、確認よろしくお願いいたします。
663c9cb

**Comment by liberta793** [comment]
確認できました!
